export { default as KpiStatsWidget } from './KpiStatsWidget'
export { default as RecentEventsWidget } from './RecentEventsWidget'
export { default as TotalEventsChartWidget } from './TotalEventsChartWidget'
export { default as BlockedByTypeWidget } from './BlockedByTypeWidget'
export { default as AllowedByTypeWidget } from './AllowedByTypeWidget'
export { default as TopUsersWidget } from './TopUsersWidget'
export { default as TopEndpointsWidget } from './TopEndpointsWidget'
export { default as VendorBreakdownWidget } from './VendorBreakdownWidget'
export { default as PolicyEventsWidget } from './PolicyEventsWidget'
export { default as DeptBlockedWidget } from './DeptBlockedWidget'
export { default as AlertVolumeWidget } from './AlertVolumeWidget'
export { default as EventTrendWidget } from './EventTrendWidget'
export { default as SuspiciousDevicesWidget } from './SuspiciousDevicesWidget'

