export { default as KpiStatsWidget } from './KpiStatsWidget'
export { default as RecentTransfersWidget } from './RecentTransfersWidget'
export { default as TotalEventsWidget } from './TotalEventsWidget'
export { default as BlockedByTypeWidget } from './BlockedByTypeWidget'
export { default as AllowedLoggedWidget } from './AllowedLoggedWidget'
export { default as TopUsersWidget } from './TopUsersWidget'
export { default as TopEndpointsWidget } from './TopEndpointsWidget'
export { default as FileTypeWidget } from './FileTypeWidget'
export { default as PolicyEventsWidget } from './PolicyEventsWidget'
export { default as DeptBlockedWidget } from './DeptBlockedWidget'
export { default as AlertVolumeWidget } from './AlertVolumeWidget'
export { default as TransferTrendWidget } from './TransferTrendWidget'
export { default as SuspiciousTransfersWidget } from './SuspiciousTransfersWidget'

